# Root netlify.toml for documentation site
[build]
  command = "echo 'Building documentation site'"
  publish = "docs"

[[redirects]]
  from = "/api/*"
  to = "https://roadtrip-mvp-792001900150.us-central1.run.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200