apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: roadtrip-backend-staging
  namespace: '460720'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      serviceAccountName: roadtrip-staging@roadtrip-460720.iam.gserviceaccount.com
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/roadtrip-460720/roadtrip-backend-staging:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: PORT
          value: '8000'
        - name: ENVIRONMENT
          value: 'staging'
        - name: ENABLE_MOCK_MODE
          value: 'true'
        - name: LOG_LEVEL
          value: 'INFO'
        - name: ALLOWED_HOSTS
          value: '*'
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            secretKeyRef:
              name: GOOGLE_CLOUD_PROJECT-staging
              key: latest
        - name: VERTEX_AI_LOCATION
          valueFrom:
            secretKeyRef:
              name: VERTEX_AI_LOCATION-staging
              key: latest
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: DATABASE_URL-staging
              key: latest
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: JWT_SECRET_KEY-staging
              key: latest
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: SECRET_KEY-staging
              key: latest
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: GOOGLE_MAPS_API_KEY-staging
              key: latest
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: OPENWEATHER_API_KEY-staging
              key: latest
        - name: TICKETMASTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: TICKETMASTER_API_KEY-staging
              key: latest
        - name: REDIS_URL
          value: 'memory://'
        - name: USE_IN_MEMORY_CACHE
          value: 'true'
        - name: DISABLE_TTS
          value: 'true'
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true