alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 15s
  external_labels:
    environment: production
    monitor: roadtrip-monitor
  scrape_interval: 15s
rule_files:
- alerts/*.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: backend
  metrics_path: /metrics
  static_configs:
  - targets:
    - backend:8000
- job_name: node
  static_configs:
  - targets:
    - node-exporter:9100
- job_name: postgres
  static_configs:
  - targets:
    - postgres-exporter:9187
- job_name: redis
  static_configs:
  - targets:
    - redis-exporter:9121
