groups:
- interval: 30s
  name: api_rules
  rules:
  - expr: rate(http_requests_total[5m])
    record: http_request_rate_5m
  - expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
    record: http_request_duration_p95
  - expr: rate(http_requests_total{status=~"5.."}[5m])
    record: error_rate_5m
