apiVersion: v1
kind: Secret
metadata:
  name: roadtrip-secrets
  namespace: production
type: Opaque
stringData:
  # This is a template - actual values should be provided during deployment
  # Use Google Secret Manager integration in production
  
  # Database credentials
  DATABASE_URL: "postgresql://roadtrip:PASSWORD@db-host:5432/roadtrip"
  
  # Redis credentials
  REDIS_URL: "redis://:PASSWORD@redis-host:6379/0"
  
  # JWT Secret
  JWT_SECRET_KEY: "your-secret-jwt-key-here"
  
  # API Keys (should be fetched from Google Secret Manager)
  GOOGLE_MAPS_API_KEY: "your-google-maps-api-key"
  OPENAI_API_KEY: "your-openai-api-key"
  TICKETMASTER_API_KEY: "your-ticketmaster-api-key"
  OPENWEATHERMAP_API_KEY: "your-openweather-api-key"
  RECREATION_GOV_API_KEY: "your-recreation-gov-api-key"
  
  # OAuth credentials
  SPOTIFY_CLIENT_ID: "your-spotify-client-id"
  SPOTIFY_CLIENT_SECRET: "your-spotify-client-secret"
---
# External Secrets Operator configuration for Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcpsm-secret-store
  namespace: production
spec:
  provider:
    gcpsm:
      projectID: "your-gcp-project-id"
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: production-roadtrip-cluster
          serviceAccountRef:
            name: roadtrip-app
---
# External Secret that pulls from Google Secret Manager
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: roadtrip-external-secrets
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: roadtrip-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: database-url
    - secretKey: REDIS_URL
      remoteRef:
        key: redis-url
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: jwt-secret-key
    - secretKey: GOOGLE_MAPS_API_KEY
      remoteRef:
        key: google-maps-api-key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: openai-api-key
    - secretKey: TICKETMASTER_API_KEY
      remoteRef:
        key: ticketmaster-api-key
    - secretKey: OPENWEATHERMAP_API_KEY
      remoteRef:
        key: openweathermap-api-key
    - secretKey: RECREATION_GOV_API_KEY
      remoteRef:
        key: recreation-gov-api-key
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: spotify-client-id
    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: spotify-client-secret