# Cloud Build configuration with comprehensive secret mappings
# This configuration ensures all secrets are properly mapped to environment variables

substitutions:
  _SERVICE_NAME: roadtrip-backend
  _REGION: us-central1
  _SERVICE_ACCOUNT: roadtrip-mvp-sa@${PROJECT_ID}.iam.gserviceaccount.com

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${BUILD_ID}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
    id: 'build-image'

  # Step 2: Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
    id: 'push-image'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run with all secrets properly mapped
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${BUILD_ID}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_SERVICE_ACCOUNT}'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '600'
      - '--concurrency'
      - '100'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - |
        ENVIRONMENT=production,
        GOOGLE_CLOUD_PROJECT=${PROJECT_ID},
        GOOGLE_AI_PROJECT_ID=${PROJECT_ID},
        GOOGLE_CLOUD_PROJECT_ID=${PROJECT_ID},
        VERTEX_AI_LOCATION=us-central1,
        LOG_LEVEL=INFO,
        CORS_ALLOWED_ORIGINS=https://*.run.app;http://localhost:3000;http://localhost:19006,
        FORCE_HTTPS=true,
        SECURE_COOKIES=true,
        PRODUCTION=true
      - '--set-secrets'
      - |
        SECRET_KEY=roadtrip-secret-key:latest,
        JWT_SECRET_KEY=roadtrip-jwt-secret:latest,
        CSRF_SECRET_KEY=roadtrip-csrf-secret:latest,
        ENCRYPTION_KEY=encryption-key:latest,
        DATABASE_URL=roadtrip-database-url:latest,
        REDIS_URL=roadtrip-redis-url:latest,
        GCS_BUCKET_NAME=roadtrip-gcs-bucket:latest,
        GOOGLE_MAPS_API_KEY=roadtrip-google-maps-key:latest,
        OPENWEATHERMAP_API_KEY=roadtrip-openweather-key:latest,
        TICKETMASTER_API_KEY=roadtrip-ticketmaster-key:latest,
        TICKETMASTER_API_SECRET=roadtrip-ticketmaster-secret:latest,
        RECREATION_GOV_API_KEY=roadtrip-recreation-key:latest,
        RECREATION_GOV_API_SECRET=roadtrip-recreation-secret:latest,
        RECREATION_GOV_ACCOUNT_ID=roadtrip-recreation-account:latest,
        SPOTIFY_CLIENT_ID=roadtrip-spotify-id:latest,
        SPOTIFY_CLIENT_SECRET=roadtrip-spotify-secret:latest,
        OPENTABLE_API_KEY=roadtrip-opentable-key:latest,
        OPENTABLE_CLIENT_ID=roadtrip-opentable-id:latest,
        OPENTABLE_CLIENT_SECRET=roadtrip-opentable-secret:latest,
        OPENTABLE_PARTNER_ID=roadtrip-opentable-partner:latest,
        VIATOR_API_KEY=roadtrip-viator-key:latest,
        VIATOR_PARTNER_ID=roadtrip-viator-partner:latest,
        RESY_API_KEY=roadtrip-resy-key:latest,
        RESY_CLIENT_ID=roadtrip-resy-id:latest,
        RESY_CLIENT_SECRET=roadtrip-resy-secret:latest,
        SHELL_RECHARGE_API_KEY=roadtrip-shell-key:latest,
        CHARGEPOINT_API_KEY=roadtrip-chargepoint-key:latest,
        CHARGEPOINT_CLIENT_ID=roadtrip-chargepoint-id:latest,
        CHARGEPOINT_CLIENT_SECRET=roadtrip-chargepoint-secret:latest,
        FLIGHT_TRACKING_API_KEY=roadtrip-flight-tracking-key:latest,
        FLIGHTSTATS_API_KEY=roadtrip-flightstats-key:latest,
        FLIGHTSTATS_APP_ID=roadtrip-flightstats-id:latest,
        FLIGHTAWARE_API_KEY=roadtrip-flightaware-key:latest,
        AVIATIONSTACK_API_KEY=roadtrip-aviationstack-key:latest,
        FLIGHTLABS_API_KEY=roadtrip-flightlabs-key:latest,
        PRIORITY_PASS_API_KEY=roadtrip-priority-pass-key:latest,
        AIRLINE_LOUNGE_API_KEY=roadtrip-airline-lounge-key:latest,
        TWILIO_ACCOUNT_SID=roadtrip-twilio-sid:latest,
        TWILIO_AUTH_TOKEN=roadtrip-twilio-token:latest,
        TWILIO_FROM_PHONE=roadtrip-twilio-phone:latest,
        SENDGRID_API_KEY=roadtrip-sendgrid-key:latest,
        TWO_FACTOR_SECRET=roadtrip-two-factor-secret:latest
    id: 'deploy-service'
    waitFor: ['push-image']

  # Step 4: Update traffic to latest
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - '${_SERVICE_NAME}'
      - '--region'
      - '${_REGION}'
      - '--to-latest'
    id: 'update-traffic'
    waitFor: ['deploy-service']

  # Step 5: Verify deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_URL=$$(gcloud run services describe ${_SERVICE_NAME} \
          --region=${_REGION} \
          --format='get(status.url)')
        
        echo "Service deployed at: $$SERVICE_URL"
        
        # Wait for service to be ready
        sleep 10
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f "$$SERVICE_URL/health" || exit 1
        
        echo "Deployment successful!"
    id: 'verify-deployment'
    waitFor: ['update-traffic']

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitutionOption: 'ALLOW_LOOSE'

timeout: '2400s'

# Images to push
images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${BUILD_ID}'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'