steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - gcr.io/$PROJECT_ID/roadtrip-backend:$COMMIT_SHA
  - .
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/roadtrip-backend:$COMMIT_SHA
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - roadtrip-api-${_ENVIRONMENT}
  - --image
  - gcr.io/$PROJECT_ID/roadtrip-backend:$COMMIT_SHA
  - --region
  - us-central1
  - --platform
  - managed
  - --set-env-vars
  - ENVIRONMENT=${_ENVIRONMENT}
substitutions:
  _ENVIRONMENT: staging
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: N1_HIGHCPU_8
timeout: 900s
