apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  api-rules.yml: |
    groups:
      - name: roadtrip_api_alerts
        interval: 30s
        rules:
          - alert: APIDown
            expr: up{job="roadtrip-api"} == 0
            for: 1m
            labels:
              severity: critical
              service: api
            annotations:
              summary: "API service is down"
              description: "The AI Road Trip API has been down for more than 1 minute"
              runbook: "https://wiki.roadtrip.app/runbooks/api-down"
              
          - alert: HighErrorRate
            expr: |
              (sum(rate(http_requests_total{status=~"5.."}[5m]))
               / sum(rate(http_requests_total[5m]))) > 0.05
            for: 5m
            labels:
              severity: critical
              service: api
            annotations:
              summary: "High error rate detected"
              description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes"
              dashboard: "https://grafana.roadtrip.app/d/api-overview"
              
          - alert: HighResponseTime
            expr: |
              histogram_quantile(0.95, 
                sum(rate(http_request_duration_seconds_bucket[5m])) by (le)
              ) > 1.0
            for: 5m
            labels:
              severity: warning
              service: api
            annotations:
              summary: "High API response time"
              description: "95th percentile response time is {{ $value }}s"
              
          - alert: HighMemoryUsage
            expr: |
              (process_resident_memory_bytes / node_memory_MemTotal_bytes) > 0.85
            for: 5m
            labels:
              severity: warning
              service: api
            annotations:
              summary: "High memory usage"
              description: "Process is using {{ $value | humanizePercentage }} of available memory"
              
  database-rules.yml: |
    groups:
      - name: roadtrip_database_alerts
        interval: 60s
        rules:
          - alert: DatabaseDown
            expr: pg_up == 0
            for: 1m
            labels:
              severity: critical
              service: database
            annotations:
              summary: "PostgreSQL is down"
              description: "Database has been unreachable for more than 1 minute"
              action: "Check database logs and connection"
              
          - alert: DatabaseConnectionPoolExhausted
            expr: |
              (db_connection_pool_used / db_connection_pool_size) > 0.9
            for: 5m
            labels:
              severity: critical
              service: database
            annotations:
              summary: "Database connection pool near exhaustion"
              description: "Connection pool is {{ $value | humanizePercentage }} full"
              
          - alert: DatabaseSlowQueries
            expr: |
              rate(pg_stat_statements_mean_time_seconds[5m]) > 1
            for: 10m
            labels:
              severity: warning
              service: database
            annotations:
              summary: "Database queries are slow"
              description: "Average query time is {{ $value }}s"
              
          - alert: DatabaseBackupFailed
            expr: |
              time() - db_backup_last_success_timestamp > 86400
            for: 1h
            labels:
              severity: critical
              service: backup
            annotations:
              summary: "Database backup failed"
              description: "No successful backup in the last 24 hours"
              action: "Check backup logs and storage"
              
  business-rules.yml: |
    groups:
      - name: roadtrip_business_alerts
        interval: 60s
        rules:
          - alert: LowBookingConversion
            expr: |
              (sum(rate(booking_completed_total[1h]))
               / sum(rate(booking_initiated_total[1h]))) < 0.05
            for: 30m
            labels:
              severity: warning
              service: business
            annotations:
              summary: "Low booking conversion rate"
              description: "Booking conversion rate is {{ $value | humanizePercentage }} in the last hour"
              
          - alert: RevenueDropDetected
            expr: |
              rate(revenue_total[1h]) < 0.8 * rate(revenue_total[1h] offset 1w)
            for: 1h
            labels:
              severity: critical
              service: business
            annotations:
              summary: "Significant revenue drop detected"
              description: "Revenue is down 20% compared to same time last week"
              
          - alert: AIServiceFailureRate
            expr: |
              (sum(rate(ai_request_errors_total[5m]))
               / sum(rate(ai_request_total[5m]))) > 0.1
            for: 5m
            labels:
              severity: critical
              service: ai
            annotations:
              summary: "High AI service failure rate"
              description: "AI service error rate is {{ $value | humanizePercentage }}"
              
  security-rules.yml: |
    groups:
      - name: roadtrip_security_alerts
        interval: 30s
        rules:
          - alert: HighFailedLoginRate
            expr: |
              sum(rate(auth_login_failed_total[5m])) > 10
            for: 5m
            labels:
              severity: warning
              service: security
            annotations:
              summary: "High failed login rate detected"
              description: "{{ $value }} failed logins per second"
              action: "Review source IPs and consider blocking"
              
          - alert: TwoFactorBypassAttempts
            expr: |
              sum(rate(auth_2fa_failed_total[5m])) > 20
            for: 5m
            labels:
              severity: critical
              service: security
            annotations:
              summary: "High 2FA failure rate"
              description: "{{ $value }} 2FA failures per second - possible bypass attempt"
              action: "Immediately investigate and block suspicious IPs"
              
          - alert: SuspiciousActivityDetected
            expr: |
              sum(rate(security_suspicious_activity_total[5m])) by (type) > 5
            for: 5m
            labels:
              severity: critical
              service: security
            annotations:
              summary: "Suspicious activity detected"
              description: "{{ $value }} suspicious {{ $labels.type }} activities per second"
              
          - alert: SSLCertificateExpiringSoon
            expr: ssl_cert_expiry_days < 30
            for: 1h
            labels:
              severity: warning
              service: ssl
            annotations:
              summary: "SSL certificate expiring soon"
              description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days"
              
          - alert: SSLCertificateExpiryCritical
            expr: ssl_cert_expiry_days < 7
            for: 1h
            labels:
              severity: critical
              service: ssl
            annotations:
              summary: "SSL certificate expiring critically soon"
              description: "SSL certificate for {{ $labels.domain }} expires in {{ $value }} days!"
              action: "Renew certificate immediately"
              
  infrastructure-rules.yml: |
    groups:
      - name: roadtrip_infrastructure_alerts
        interval: 60s
        rules:
          - alert: NodeDown
            expr: up{job="kubernetes-nodes"} == 0
            for: 5m
            labels:
              severity: critical
              service: infrastructure
            annotations:
              summary: "Kubernetes node is down"
              description: "Node {{ $labels.node }} has been down for 5 minutes"
              
          - alert: DiskSpaceLow
            expr: |
              (node_filesystem_avail_bytes{mountpoint="/"}
               / node_filesystem_size_bytes{mountpoint="/"}) < 0.15
            for: 10m
            labels:
              severity: warning
              service: infrastructure
            annotations:
              summary: "Low disk space"
              description: "Only {{ $value | humanizePercentage }} disk space remaining on {{ $labels.instance }}"
              
          - alert: HighCPUUsage
            expr: |
              avg(rate(process_cpu_seconds_total[5m])) > 0.8
            for: 10m
            labels:
              severity: warning
              service: infrastructure
            annotations:
              summary: "High CPU usage"
              description: "CPU usage is {{ $value | humanizePercentage }}"
              
          - alert: PodCrashLooping
            expr: |
              rate(kube_pod_container_status_restarts_total[15m]) > 0
            for: 5m
            labels:
              severity: critical
              service: infrastructure
            annotations:
              summary: "Pod is crash looping"
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping"
              
  cache-rules.yml: |
    groups:
      - name: roadtrip_cache_alerts
        interval: 60s
        rules:
          - alert: RedisDown
            expr: up{job="redis"} == 0
            for: 1m
            labels:
              severity: critical
              service: redis
            annotations:
              summary: "Redis is down"
              description: "Redis has been down for more than 1 minute"
              
          - alert: LowCacheHitRate
            expr: |
              (redis_cache_hits_total
               / (redis_cache_hits_total + redis_cache_misses_total)) < 0.7
            for: 15m
            labels:
              severity: warning
              service: cache
            annotations:
              summary: "Low cache hit rate"
              description: "Cache hit rate is {{ $value | humanizePercentage }}"
              
          - alert: RedisMemoryHigh
            expr: |
              redis_memory_used_bytes / redis_memory_max_bytes > 0.9
            for: 10m
            labels:
              severity: warning
              service: redis
            annotations:
              summary: "Redis memory usage high"
              description: "Redis is using {{ $value | humanizePercentage }} of allocated memory"