auth_enabled: false
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
schema_config:
  configs:
  - from: '2025-01-01'
    index:
      period: 24h
      prefix: index_
    object_store: filesystem
    schema: v11
    store: boltdb
server:
  http_listen_port: 3100
storage_config:
  boltdb:
    directory: /loki/index
  filesystem:
    directory: /loki/chunks
