clients:
- url: http://loki:3100/loki/api/v1/push
positions:
  filename: /tmp/positions.yaml
scrape_configs:
- job_name: backend
  pipeline_stages:
  - json:
      expressions:
        level: level
        message: message
        service: service
        timestamp: timestamp
  - labels:
      level: null
      service: null
  - timestamp:
      format: RFC3339
      source: timestamp
  static_configs:
  - labels:
      __path__: /var/log/roadtrip/*.log
      job: backend
    targets:
    - localhost
server:
  grpc_listen_port: 0
  http_listen_port: 9080
